server:
  port: 8502

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8501/eureka/

spring:
  application:
    name: server-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/wslsw/SpringCloudConfig/
          username: 
          password: 
          search-paths: config
    stream:
      kafka:
        binder:
          zk-nodes: localhost:2181
          brokers: localhost:9092
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

management:
  security:
    enabled: false