spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:orcl 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j

mybatis:
  type-aliases-package: com.diit.common.pojo
  mapper-locations: classpath:mapper/*.xml
  
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  
#mapper:
#  mappers: com.example.util.MyMapper
#  not-empty: false
#  identity: ORACLE

# swagger2
swagger2.package: com.diit.service.user

# Redis
redisKey:
  # 缓存时间 默认半小时
  expire_time: 1800
  prefix:
    # 首页广告
    index_ad: 'INDEX_AD'